version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo-pc
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--bind_ip_all"]
    

volumes:
  mongo-data: